<template>
  <section class="mx-auto max-w-7xl px-3 py-10 sm:px-6"><div class="flex flex-wrap items-end justify-between gap-5"><div><p class="text-xs uppercase tracking-[.3em] text-cyan-200">Recognition</p><h1 class="mt-3 text-3xl font-black">Certificates</h1><p class="mt-3 text-slate-400">Issue and maintain participant certificates.</p></div><button class="primary" @click="openCreate">+ Issue certificate</button></div>
    <div class="mt-8 grid gap-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_8rem]"><label class="field"><span>Event</span><select v-model="eventId"><option v-for="event in events" :key="event.id" :value="event.id">{{event.name}}</option></select></label><label class="field"><span>Search</span><input v-model.trim="search" type="search" placeholder="Certificate, recipient, or title"></label><label class="field"><span>Per page</span><select v-model.number="pageSize"><option :value="10">10</option><option :value="20">20</option><option :value="50">50</option></select></label></div><p v-if="feedback" class="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/10 p-4">{{feedback}}</p>
    <div class="mt-6 overflow-x-auto rounded-[2rem] border border-white/10 bg-slate-950/45 data-table-shell"><table class="w-full min-w-full text-left md:min-w-[900px]"><thead><tr><th>Certificate</th><th>User</th><th>Issued</th><th>Download</th><th class="text-right">Actions</th></tr></thead><tbody><tr v-if="loading"><td colspan="5" class="py-12 text-center">Loading...</td></tr><tr v-else-if="!filteredItems.length"><td colspan="5" class="py-12 text-center">No certificates issued.</td></tr><tr v-for="item in paginatedItems" v-else :key="item.id"><td data-label="Certificate"><strong class="break-words">{{item.title}}</strong><small class="break-words">{{item.certificate_number}}</small></td><td data-label="User" class="break-words">{{userLabel(item.user_id)}}</td><td data-label="Issued">{{formatDate(item.issued_at)}}</td><td data-label="Download"><a v-if="item.download_url" :href="item.download_url" target="_blank" rel="noopener" class="break-all text-cyan-200">Open file</a><span v-else>—</span></td><td data-label="Actions" class="cell-actions"><div class="flex flex-wrap justify-end gap-2"><NuxtLink class="table-button text-cyan-200" :to="{ path: '/admin/translations', query: { entity_type: 'certificate', entity_id: item.id } }">Chinese translation</NuxtLink><button class="table-button" @click="openEdit(item)">Edit</button><button class="table-button text-red-200" @click="remove(item)">Delete</button></div></td></tr></tbody></table></div>
    <div class="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-400"><span>Showing {{ pageStart }}–{{ pageEnd }} of {{ tableMeta.total }}</span><div class="flex items-center gap-3"><button class="table-button" :disabled="currentPage <= 1" @click="currentPage--">Previous</button><span>Page {{ currentPage }} of {{ totalPages }}</span><button class="table-button" :disabled="currentPage >= totalPages" @click="currentPage++">Next</button></div></div>
    <Teleport to="body"><div v-if="modalOpen" class="backdrop" @click.self="close"><form class="modal" @submit.prevent="save"><header><div><p class="text-xs uppercase tracking-[.25em] text-cyan-200">Certificate editor</p><h2>{{editingId?'Update':'Issue'}} certificate</h2></div><button type="button" @click="close">×</button></header><main><label class="field"><span>Recipient</span><select v-model="form.user_id" required><option value="" disabled>Select user</option><option v-for="user in users" :key="user.id" :value="user.id">{{user.full_name||user.email}} — {{user.email}}</option></select></label><div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Certificate number</span><input v-model.trim="form.certificate_number" required /></label><label class="field"><span>Issued at</span><input v-model="form.issued_at" type="datetime-local" /></label></div><label class="field"><span>Title</span><input v-model.trim="form.title" required /></label><label class="field"><span>Download URL</span><input v-model.trim="form.download_url" type="url" /></label></main><footer><button type="button" class="secondary" @click="close">Cancel</button><button class="primary" :disabled="saving">{{saving?'Saving...':'Save'}}</button></footer></form></div></Teleport>
  </section>
</template>
<script setup lang="ts">
import { useTableReload } from '~/composables/useTableReload';
import{useAdminOperations,type AdminUserItem,type CertificatePayload}from'~/composables/useAdminOperations';import{useEvent,type EventItem}from'~/composables/useEvent';import type{CertificateItem}from'~/composables/useEventUpdates';
definePageMeta({middleware:['auth','admin']});useSeoMeta({title:'Manage Certificates | Hari Santri 2026'});const api=useAdminOperations(),{getEvents}=useEvent();const{data:eventResponse}=await useAsyncData('certificate-events',()=>getEvents(1,100));const events=computed<EventItem[]>(()=>eventResponse.value?.data||[]),eventId=ref(events.value[0]?.id||''),users=ref<AdminUserItem[]>([]),items=ref<CertificateItem[]>([]),loading=ref(false),saving=ref(false),modalOpen=ref(false),editingId=ref(''),feedback=ref('');type Form={user_id:string;certificate_number:string;title:string;download_url:string;issued_at:string};const empty=():Form=>({user_id:'',certificate_number:'',title:'Certificate of Attendance',download_url:'',issued_at:''}),form=reactive(empty());const errorText=(e:unknown)=>(e as {data?:{message?:string}}).data?.message||(e instanceof Error?e.message:'Operation failed.');const local=(v?:string|null)=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const search=ref(''),currentPage=ref(1),pageSize=ref(20);const filteredItems=computed(()=>items.value);const tableMeta=reactive({total:0,pages:0});const totalPages=computed(()=>Math.max(1,tableMeta.pages));const paginatedItems=computed(()=>items.value);const pageStart=computed(()=>items.value.length?(currentPage.value-1)*pageSize.value+1:0);const pageEnd=computed(()=>Math.min((currentPage.value-1)*pageSize.value+items.value.length,tableMeta.total));
let tableRequestId=0;const load=async()=>{const requestId=++tableRequestId;if(!eventId.value)return;loading.value=true;try{const[result,userResult]=await Promise.all([api.getAdminCertificates(eventId.value,{search:search.value,page:currentPage.value,size:pageSize.value}),api.getUsers(1,100)]);if(requestId!==tableRequestId)return;items.value=result.data||[];Object.assign(tableMeta,{total:result.meta?.total??0,pages:result.meta?.pages??0});users.value=userResult.data||[];}catch(e){if(requestId!==tableRequestId)return;feedback.value=errorText(e);}finally{if(requestId===tableRequestId)loading.value=false;}};const openCreate=()=>{editingId.value='';Object.assign(form,empty());modalOpen.value=true;};const openEdit=(item:CertificateItem)=>{editingId.value=item.id;Object.assign(form,{user_id:item.user_id||'',certificate_number:item.certificate_number,title:item.title,download_url:item.download_url||'',issued_at:local(item.issued_at)});modalOpen.value=true;};const close=()=>modalOpen.value=false;const save=async()=>{saving.value=true;const payload:CertificatePayload={event_id:eventId.value,user_id:form.user_id,certificate_number:form.certificate_number,title:form.title,download_url:form.download_url||null,issued_at:form.issued_at?new Date(form.issued_at).toISOString():null};try{if(editingId.value)await api.updateCertificate(editingId.value,payload);else await api.createCertificate(payload);feedback.value='Certificate saved.';close();await load();}catch(e){feedback.value=errorText(e);}finally{saving.value=false;}};const remove=async(item:CertificateItem)=>{if(!confirm(`Delete certificate "${item.certificate_number}"?`))return;try{await api.deleteCertificate(item.id);await load();}catch(e){feedback.value=errorText(e);}};const userLabel=(id?:string)=>{const user=users.value.find(item=>item.id===id);return user?.full_name||user?.email||id||'—';};watch(eventId,()=>{currentPage.value=1;void load();});useTableReload(search,currentPage,pageSize,load);watch(totalPages,value=>{if(currentPage.value>value)currentPage.value=value;});if(eventId.value)await load();const formatDate=(v?:string|null)=>v?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(new Date(v)):'—';
</script>
<style scoped>
section { font-family: 'Plus Jakarta Sans', 'Segoe UI', sans-serif; }
th{padding:1rem 1.25rem;background:#ffffff0a;font-size:.68rem;text-transform:uppercase;letter-spacing:.18em;color:#94a3b8}td{padding:1rem 1.25rem;border-top:1px solid #ffffff12;color:#cbd5e1}td strong,td small{display:block}td small{margin-top:.3rem;color:#64748b}.field span{display:block;margin-bottom:.5rem;font-size:.875rem;color:#cbd5e1}.field input,.field select{width:100%;border:1px solid #ffffff1a;border-radius:1rem;background:#020617d9;padding:.75rem 1rem;color:white}.primary,.secondary,.table-button{border-radius:999px;padding:.7rem 1.15rem;font-weight:800}.primary{background:#67e8f9;color:#083344}.secondary,.table-button{border:1px solid #ffffff26}.table-button{padding:.45rem .8rem;font-size:.75rem}.backdrop{position:fixed;inset:0;z-index:100;display:flex;align-items:center;justify-content:center;padding:1rem;background:#020617cc;backdrop-filter:blur(12px)}.modal{width:min(100%,44rem);overflow:hidden;border:1px solid #ffffff21;border-radius:2rem;background:linear-gradient(145deg,#071a36,#020d20)}.modal header,.modal footer{display:flex;align-items:center;justify-content:space-between;padding:1.25rem 1.75rem;border-bottom:1px solid #ffffff1a}.modal h2{margin-top:.5rem;font-size:1.5rem;font-weight:900}.modal header button{font-size:1.75rem}.modal main{display:grid;gap:1rem;padding:1.5rem 1.75rem}.modal footer{justify-content:flex-end;gap:.75rem;border-top:1px solid #ffffff1a;border-bottom:0}

@media (max-width: 767px) {
  .data-table-shell { overflow: visible; }
  .data-table-shell table, .data-table-shell thead, .data-table-shell tbody, .data-table-shell tr, .data-table-shell th, .data-table-shell td { display: block; width: 100%; box-sizing: border-box; }
  .data-table-shell thead { display: none; }
  .data-table-shell tbody { display: grid; gap: 0.75rem; padding: 0.75rem; }
  .data-table-shell tr { border: 1px solid rgba(255,255,255,0.08); border-radius: 1.1rem; background: rgba(15,23,42,0.72); padding: 0.8rem; }
  .data-table-shell td { border: 0; padding: 0.35rem 0; display: flex; justify-content: space-between; gap: 0.75rem; font-size: 0.8rem; }
  .data-table-shell td::before { content: attr(data-label); color: #94a3b8; font-size: 0.64rem; letter-spacing: 0.14em; text-transform: uppercase; width: 36%; flex-shrink: 0; }
  .data-table-shell td > * { flex: 1; min-width: 0; }

  .data-table-shell td.cell-actions { flex-direction: column; align-items: stretch; }
  .data-table-shell td.cell-actions::before { width: 100%; margin-bottom: 0.25rem; }
  .data-table-shell td.cell-actions > div { justify-content: stretch; }
  .data-table-shell td.cell-actions .table-button { width: 100%; }

  .modal { width: min(100%, 32rem); }
  .modal main, .modal header, .modal footer { padding-inline: 1rem; }
  .modal footer { flex-direction: column; }
  .modal footer button { width: 100%; }
}
</style>
