<template>
  <section class="mx-auto max-w-7xl px-3 py-10 sm:px-6 lg:px-8">
    <header class="flex flex-wrap items-end justify-between gap-5">
      <div><p class="text-sm uppercase tracking-[.3em] text-amber-200">Event operations</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Host & Committee</h1><p class="mt-3 text-sm text-slate-300">Manage the public Host page, ordering, publication, photos, and bilingual content.</p></div>
      <div class="flex gap-3"><NuxtLink to="/#tentang" class="action-secondary">View event overview</NuxtLink><button class="action-primary" :disabled="!selectedEventId" @click="openCreate">+ New member</button></div>
    </header>
    <p v-if="feedback" class="mt-5 rounded-2xl border p-4 text-sm" :class="feedbackTone === 'error' ? 'border-red-300/30 bg-red-950/30 text-red-100' : 'border-emerald-300/30 bg-emerald-950/30 text-emerald-100'">{{ feedback }}</p>
    <div class="mt-8 flex flex-col gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-4 sm:flex-row sm:items-end">
      <label class="field flex-1"><span>Event</span><select v-model="selectedEventId"><option v-for="event in events" :key="event.id" :value="event.id">{{ event.name }}</option></select></label>
      <label class="field flex-1"><span>Search</span><input v-model.trim="search" placeholder="Name, role, group, or organization"></label>
      <label class="field sm:w-32"><span>Per page</span><select v-model.number="pageSize"><option :value="10">10</option><option :value="20">20</option><option :value="50">50</option></select></label>
      <span class="pb-3 text-sm text-slate-400">{{ tableMeta.total }} members</span>
    </div>
    <div class="mt-6 overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/45"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left"><thead class="border-b border-white/10 text-xs uppercase tracking-wider text-slate-400"><tr><th class="p-5">Order</th><th class="p-5">Member</th><th class="p-5">Group</th><th class="p-5">Status</th><th class="p-5 text-right">Actions</th></tr></thead><tbody class="divide-y divide-white/10">
      <tr v-if="loading"><td colspan="5" class="p-10 text-center text-slate-400">Loading committee…</td></tr><tr v-else-if="!filteredMembers.length"><td colspan="5" class="p-10 text-center text-slate-400">No committee members found.</td></tr>
      <tr v-for="member in paginatedMembers" v-else :key="member.id"><td class="p-5 text-amber-200">{{ member.display_order ?? 0 }}</td><td class="p-5"><div class="flex items-center gap-3"><img v-if="member.profile_photo_url" :src="mediaUrl(member.profile_photo_url)" :alt="member.full_name" class="h-12 w-12 rounded-xl object-cover"><div v-else class="grid h-12 w-12 place-items-center rounded-xl bg-amber-300/10 font-bold text-amber-200">{{ initials(member.full_name) }}</div><div><strong class="text-white">{{ member.full_name }}</strong><p class="mt-1 text-xs text-slate-400">{{ member.role_title || 'Committee member' }} · {{ member.organization_name || '—' }}</p></div></div></td><td class="p-5 text-sm text-slate-300">{{ member.committee_group || '—' }}</td><td class="p-5"><span class="status-pill" :class="member.status === 'published' ? 'status-live' : 'status-draft'">{{ member.status }}</span><span class="status-pill ml-2" :class="translationStatuses[member.id] === 'complete' ? 'translation-complete' : translationStatuses[member.id] === 'error' ? 'translation-error' : 'translation-missing'">ZH {{ translationStatuses[member.id] === 'complete' ? 'complete' : translationStatuses[member.id] === 'loading' ? 'checking' : translationStatuses[member.id] === 'error' ? 'unknown' : 'missing' }}</span><span v-if="member.is_featured" class="ml-2 text-amber-200">★</span></td><td class="p-5"><div class="flex justify-end gap-2"><button class="table-button" @click="openEdit(member)">Edit</button><button class="table-button danger" @click="removeMember(member)">Delete</button></div></td></tr>
    </tbody></table></div></div>
    <div class="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-400"><span>Showing {{ pageStart }}–{{ pageEnd }} of {{ tableMeta.total }}</span><div class="flex items-center gap-3"><button class="table-button" :disabled="currentPage <= 1" @click="currentPage--">Previous</button><span>Page {{ currentPage }} of {{ totalPages }}</span><button class="table-button" :disabled="currentPage >= totalPages" @click="currentPage++">Next</button></div></div>

    <Teleport to="body"><div v-if="modalOpen" class="modal-backdrop"><form class="modal-card" @submit.prevent="saveMember"><header class="flex items-start justify-between border-b border-white/10 p-6"><div><p class="text-xs uppercase tracking-[.24em] text-amber-200">Host editor</p><h2 class="mt-2 text-2xl font-black">{{ editingId ? 'Update member' : 'Create member' }}</h2></div><button type="button" class="modal-close" @click="closeModal">×</button></header>
      <div class="max-h-[72vh] overflow-y-auto p-6"><div class="mb-5 flex rounded-full border border-white/10 bg-slate-950/60 p-1"><button type="button" class="language-tab" :class="activeTab === 'en' && 'active'" @click="activeTab='en'">English — Source</button><button type="button" class="language-tab" :class="activeTab === 'zh-CN' && 'active'" :disabled="!editingId" @click="activeTab='zh-CN'">简体中文</button></div>
        <div v-if="activeTab === 'en'" class="space-y-4"><div class="flex items-center gap-4 rounded-2xl border p-4" :class="photoError ? 'border-red-300/40 bg-red-950/20' : 'border-white/10'"><img v-if="photoPreview" :src="photoPreview" alt="Preview" class="h-24 w-24 rounded-2xl object-cover"><div v-else class="grid h-24 w-24 place-items-center rounded-2xl bg-amber-300/10 text-2xl font-bold text-amber-200">{{ initials(form.full_name || 'Host') }}</div><div><b>Profile photo</b><p class="mt-1 text-xs text-slate-400">JPG, PNG, or WebP · max 5 MB</p><p v-if="photoError" role="alert" class="mt-2 text-sm font-semibold text-red-200">{{ photoError }}</p><label class="mt-3 inline-flex cursor-pointer rounded-full bg-white/10 px-4 py-2 text-xs font-bold">Choose photo<input type="file" class="sr-only" accept="image/jpeg,image/png,image/webp" @change="selectPhoto"></label></div></div>
          <label class="field"><span>Full name</span><input v-model.trim="form.full_name" required></label><div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Role title</span><input v-model.trim="form.role_title"></label><label class="field"><span>Committee group</span><input v-model.trim="form.committee_group" placeholder="Organizing Committee"></label></div><label class="field"><span>Organization</span><input v-model.trim="form.organization_name"></label><label class="field"><span>Biography</span><textarea v-model.trim="form.biography" rows="5" /></label><div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Display order</span><input v-model.number="form.display_order" type="number" min="0" required></label><label class="field"><span>Status</span><select v-model="form.status"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><label class="flex gap-3 text-sm"><input v-model="form.is_featured" type="checkbox"> Featured member</label>
        </div><div v-else class="space-y-4"><p class="rounded-2xl border border-cyan-300/15 bg-cyan-300/5 p-4 text-sm text-slate-300">Full name, photo, order, featured state, and publication status remain canonical.</p><div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Role title (简体中文)</span><input v-model.trim="zhForm.role_title"></label><label class="field"><span>Committee group (简体中文)</span><input v-model.trim="zhForm.committee_group"></label></div><label class="field"><span>Organization (简体中文)</span><input v-model.trim="zhForm.organization_name"></label><label class="field"><span>Biography (简体中文)</span><textarea v-model.trim="zhForm.biography" rows="5" /></label><button v-if="translationExists" type="button" class="danger-button" @click="deleteTranslation">Delete Chinese translation</button></div>
      </div><footer class="flex justify-end gap-3 border-t border-white/10 p-6"><button type="button" class="action-secondary" @click="closeModal">Cancel</button><button class="action-primary" :disabled="saving">{{ saving ? 'Saving…' : 'Save member' }}</button></footer></form></div></Teleport>
  </section>
</template>

<script setup lang="ts">
import { useTableReload } from '~/composables/useTableReload';
import { useAdminContent, type CommitteeMemberMutationPayload } from '~/composables/useAdminContent';
import { useEvent, type CommitteeMemberItem, type EventItem } from '~/composables/useEvent';
definePageMeta({ middleware:['auth','admin'] }); useSeoMeta({ title:'Manage Hosts | Hari Santri 2026' });
const admin=useAdminContent(); const {getEvents}=useEvent(); const {mediaUrl}=useMediaUrl();
const {data:eventResponse}=await useAsyncData('admin-host-events',()=>getEvents(1,100)); const events=computed<EventItem[]>(()=>eventResponse.value?.data||[]); const selectedEventId=ref(''); const members=ref<CommitteeMemberItem[]>([]),loading=ref(false),search=ref(''),feedback=ref(''),feedbackTone=ref<'success'|'error'>('success');
const filteredMembers=computed(()=>members.value);
const currentPage=ref(1),pageSize=ref(20);const tableMeta=reactive({total:0,pages:0});const totalPages=computed(()=>Math.max(1,tableMeta.pages));const paginatedMembers=computed(()=>members.value);const pageStart=computed(()=>members.value.length?(currentPage.value-1)*pageSize.value+1:0);const pageEnd=computed(()=>Math.min((currentPage.value-1)*pageSize.value+members.value.length,tableMeta.total));
const emptyForm=():CommitteeMemberMutationPayload=>({event_id:'',full_name:'',role_title:'',committee_group:'',organization_name:'',biography:'',display_order:0,is_featured:false,status:'draft'}); const form=reactive(emptyForm()); const emptyZh=()=>({role_title:'',committee_group:'',organization_name:'',biography:''}); const zhForm=reactive(emptyZh());
type TranslationStatus='loading'|'complete'|'missing'|'error'; const translationStatuses=ref<Record<string,TranslationStatus>>({});
const modalOpen=ref(false),editingId=ref(''),saving=ref(false),activeTab=ref<'en'|'zh-CN'>('en'),translationExists=ref(false),selectedPhoto=ref<File|null>(null),photoPreview=ref(''),photoError=ref('');
const initials=(name:string)=>name.trim().split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase(); const apiError=(error:unknown)=>{const value=error as {data?:{message?:string;request_id?:string;errors?:Array<{message:string}>}};const message=value.data?.errors?.[0]?.message||value.data?.message||(error instanceof Error?error.message:'Committee operation failed.');return value.data?.request_id?`${message} (Request ID: ${value.data.request_id})`:message;};
const clearPhoto=()=>{if(photoPreview.value.startsWith('blob:'))URL.revokeObjectURL(photoPreview.value);selectedPhoto.value=null;photoPreview.value='';photoError.value='';}; const reset=()=>{editingId.value='';activeTab.value='en';translationExists.value=false;clearPhoto();Object.assign(form,emptyForm(),{event_id:selectedEventId.value});Object.assign(zhForm,emptyZh());};
const loadTranslationStatuses=async()=>{translationStatuses.value=Object.fromEntries(members.value.map(item=>[item.id,'loading'])) as Record<string,TranslationStatus>;await Promise.all(members.value.map(async item=>{try{const rows=(await admin.getContentTranslations('committee_member',item.id)).data||[];translationStatuses.value[item.id]=rows.some(row=>row.locale==='zh-CN')?'complete':'missing';}catch{translationStatuses.value[item.id]='error';}}));};
let tableRequestId=0;const load=async()=>{const requestId=++tableRequestId;if(!selectedEventId.value){members.value=[];return;}loading.value=true;try{const result=await admin.getCommittee(selectedEventId.value,'en',{search:search.value,page:currentPage.value,size:pageSize.value});if(requestId!==tableRequestId)return;members.value=result.data||[];Object.assign(tableMeta,{total:result.meta?.total??0,pages:result.meta?.pages??0});await loadTranslationStatuses();}catch(error){if(requestId!==tableRequestId)return;feedbackTone.value='error';feedback.value=apiError(error);}finally{if(requestId===tableRequestId)loading.value=false;}};
const openCreate=()=>{reset();modalOpen.value=true;}; const openEdit=async(member:CommitteeMemberItem)=>{reset();editingId.value=member.id;Object.assign(form,{event_id:member.event_id,full_name:member.full_name,role_title:member.role_title||'',committee_group:member.committee_group||'',organization_name:member.organization_name||'',biography:member.biography||'',display_order:member.display_order||0,is_featured:Boolean(member.is_featured),status:(member.status||'draft') as CommitteeMemberMutationPayload['status']});photoPreview.value=member.profile_photo_url?mediaUrl(member.profile_photo_url):'';modalOpen.value=true;try{const rows=(await admin.getContentTranslations('committee_member',member.id)).data||[];const translation=rows.find(row=>row.locale==='zh-CN');translationExists.value=Boolean(translation);const fields=translation?.fields||{};Object.assign(zhForm,{role_title:String(fields.role_title||''),committee_group:String(fields.committee_group||''),organization_name:String(fields.organization_name||''),biography:String(fields.biography||'')});}catch{/* translation remains optional */}}; const closeModal=()=>{modalOpen.value=false;reset();};
const selectPhoto=(event:Event)=>{const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;photoError.value='';if(file.size>5*1024*1024){photoError.value=`Photo is too large (${(file.size/1024/1024).toFixed(1)} MB). Maximum allowed size is 5 MB.`;input.value='';return;}if(file.size===0){photoError.value='The selected photo is empty. Please choose another file.';input.value='';return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){photoError.value='Unsupported photo format. Please use JPG, PNG, or WebP.';input.value='';return;}clearPhoto();selectedPhoto.value=file;photoPreview.value=URL.createObjectURL(file);};
const hasZh=()=>Object.values(zhForm).some(value=>value.trim()); const zhPayload=()=>({role_title:zhForm.role_title.trim(),committee_group:zhForm.committee_group.trim(),organization_name:zhForm.organization_name.trim(),biography:zhForm.biography.trim()}); const saveMember=async()=>{if(saving.value)return;saving.value=true;let memberId=editingId.value;let sourceSaved=false;let photoSaved=!selectedPhoto.value;try{const payload={...form,event_id:selectedEventId.value,role_title:form.role_title||null,committee_group:form.committee_group||null,organization_name:form.organization_name||null,biography:form.biography||null};const result=memberId?await admin.updateCommitteeMember(memberId,payload):await admin.createCommitteeMember(payload);memberId=result.data.id;editingId.value=memberId;sourceSaved=true;if(selectedPhoto.value){await admin.uploadCommitteePhoto(memberId,selectedPhoto.value);photoSaved=true;}if(hasZh()){try{await admin.saveContentTranslation('committee_member',memberId,zhPayload());translationExists.value=true;}catch(error){feedbackTone.value='error';feedback.value=`English source${photoSaved?' and photo':''} saved, but the Chinese translation failed. ${apiError(error)}`;activeTab.value='zh-CN';await load();return;}}feedbackTone.value='success';feedback.value=hasZh()?'English source and Chinese translation saved.':'English source saved. Chinese translation remains missing.';closeModal();await load();}catch(error){feedbackTone.value='error';feedback.value=sourceSaved&&!photoSaved?`Host data was saved, but photo upload failed. ${apiError(error)}`:apiError(error);if(sourceSaved)await load();}finally{saving.value=false;}};
const deleteTranslation=async()=>{if(!editingId.value||!confirm('Delete this Chinese translation?'))return;try{await admin.deleteContentTranslation('committee_member',editingId.value);Object.assign(zhForm,emptyZh());translationExists.value=false;feedbackTone.value='success';feedback.value='Chinese translation deleted.';}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}}; const removeMember=async(member:CommitteeMemberItem)=>{if(!confirm(`Delete ${member.full_name}?`))return;try{await admin.deleteCommitteeMember(member.id);feedbackTone.value='success';feedback.value='Committee member deleted.';await load();}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}};
watch(events,value=>{if(!selectedEventId.value)selectedEventId.value=value[0]?.id||'';},{immediate:true});watch(selectedEventId,()=>{currentPage.value=1;void load();},{immediate:true});useTableReload(search,currentPage,pageSize,load);watch(totalPages,value=>{if(currentPage.value>value)currentPage.value=value;});onBeforeUnmount(clearPhoto);
</script>

<style scoped>
.field{display:block;font-size:.875rem;color:#cbd5e1}.field span{display:block;margin-bottom:.5rem}.field input,.field select,.field textarea{width:100%;border:1px solid rgba(255,255,255,.12);border-radius:1rem;background:#020d20;padding:.75rem 1rem;color:#fff;outline:none}.action-primary,.action-secondary,.table-button{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:.7rem 1.15rem;font-size:.8rem;font-weight:700}.action-primary{background:#e6c477;color:#071a34}.action-secondary,.table-button{border:1px solid rgba(255,255,255,.16);color:#e2e8f0}.table-button{padding:.45rem .85rem}.danger{border-color:rgba(252,165,165,.3);color:#fecaca}.status-pill{display:inline-flex;border-radius:999px;padding:.35rem .7rem;font-size:.65rem;font-weight:800;text-transform:uppercase}.status-live,.translation-complete{background:rgba(52,211,153,.12);color:#a7f3d0}.status-draft,.translation-missing{background:rgba(251,191,36,.12);color:#fde68a}.translation-error{background:rgba(248,113,113,.12);color:#fecaca}.modal-backdrop{position:fixed;inset:0;z-index:100;display:flex;align-items:center;justify-content:center;background:rgba(2,6,23,.8);padding:1rem;backdrop-filter:blur(12px)}.modal-card{width:min(100%,50rem);overflow:hidden;border:1px solid rgba(255,255,255,.13);border-radius:2rem;background:linear-gradient(145deg,#071a36,#020d20);color:#fff}.modal-close{font-size:1.5rem;color:#cbd5e1}.language-tab{flex:1;border-radius:999px;padding:.65rem;color:#94a3b8}.language-tab.active{background:rgba(230,196,119,.15);color:#fde68a}.danger-button{border:1px solid rgba(252,165,165,.3);border-radius:999px;padding:.7rem 1rem;color:#fecaca}
@media (max-width:767px){.overflow-x-auto{overflow:visible}.overflow-x-auto table,.overflow-x-auto thead,.overflow-x-auto tbody,.overflow-x-auto tr,.overflow-x-auto th,.overflow-x-auto td{display:block;box-sizing:border-box;width:100%;min-width:0}.overflow-x-auto thead{display:none}.overflow-x-auto tbody{display:grid;gap:.75rem;padding:.75rem}.overflow-x-auto tr{border:1px solid rgba(255,255,255,.1);border-radius:1rem;padding:.85rem}.overflow-x-auto td{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem;padding:.4rem 0}.overflow-x-auto td::before{flex:0 0 32%;color:#94a3b8;font-size:.65rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.overflow-x-auto td:nth-child(1)::before{content:'Order'}.overflow-x-auto td:nth-child(2)::before{content:'Member'}.overflow-x-auto td:nth-child(3)::before{content:'Group'}.overflow-x-auto td:nth-child(4)::before{content:'Status'}.overflow-x-auto td:nth-child(5)::before{content:'Actions'}.overflow-x-auto td:last-child>div{justify-content:flex-end;flex-wrap:wrap}}
</style>
