<template>
  <section class="mx-auto max-w-5xl px-3 py-10 sm:px-6">
    <div class="flex flex-wrap items-end justify-between gap-4">
      <div><p class="text-sm uppercase tracking-[.3em] text-amber-200">{{ copy.eyebrow }}</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">{{ copy.title }}</h1><p class="mt-3 text-sm text-slate-300">{{ copy.description }}</p></div>
      <NuxtLink to="/tickets" class="rounded-full border border-white/20 px-5 py-3 text-sm font-semibold">{{ copy.addPackage }}</NuxtLink>
    </div>
    <div v-if="loading" class="glass-card mt-8 rounded-[2rem] p-7 text-slate-300">{{ copy.loading }}</div>
    <div v-else-if="errorMessage" class="mt-8 rounded-3xl border border-red-400/30 bg-red-950/30 p-6 text-red-100">{{ errorMessage }}</div>
    <div v-else-if="!items.length" class="glass-card mt-8 rounded-[2rem] p-7"><h2 class="text-xl font-bold">{{ copy.empty }}</h2><p class="mt-2 text-slate-400">{{ pendingOrders.length ? copy.pendingSaved : copy.choosePackage }}</p><NuxtLink v-if="!pendingOrders.length" to="/tickets" class="mt-6 inline-flex rounded-full bg-amber-300 px-5 py-3 font-semibold text-slate-950">{{ copy.browse }}</NuxtLink></div>
    <div v-else class="mt-8 grid gap-6 lg:grid-cols-[1fr_22rem]">
      <div class="space-y-4">
        <article v-for="item in items" :key="item.product_id" class="glass-card flex flex-col gap-4 rounded-3xl p-5 sm:flex-row sm:items-center sm:justify-between">
          <div class="min-w-0"><p class="text-xs uppercase tracking-[.2em] text-amber-200">{{ item.product?.product_type || copy.package }}</p><h2 class="mt-2 break-words text-xl font-bold">{{ item.product?.name || item.product_name || item.name || copy.defaultPackage }}</h2><p class="mt-2 text-sm text-slate-400">{{ copy.quantity }}: {{ item.quantity }}</p></div>
          <div class="sm:text-right"><p class="break-words text-lg font-bold">{{ usd(displayUnitPrice(item.product_id) * item.quantity) }}</p><LocalCurrencyAmounts :amount="displayItemIdr(item.product_id, item.quantity)" compact /><button class="mt-3 text-sm font-semibold text-red-300 disabled:opacity-50" :disabled="removingId === item.product_id" @click="remove(item.product_id)">{{ removingId === item.product_id ? copy.removing : copy.remove }}</button></div>
        </article>
      </div>
      <aside class="glass-card h-fit rounded-[2rem] p-6"><p class="text-xs uppercase tracking-[.25em] text-slate-400">{{ copy.summary }}</p><div class="mt-5 flex justify-between text-sm text-slate-300"><span>{{ copy.items }}</span><span>{{ itemCount }}</span></div><div class="mt-5 flex items-end justify-between border-t border-white/10 pt-5"><span class="text-slate-400">{{ copy.total }}</span><strong class="text-2xl text-amber-200">{{ usd(displayTotal) }}</strong></div><LocalCurrencyAmounts :amount="displayIdrTotal" show-rate /><p v-if="mainPackageRequired" class="mt-4 rounded-xl border border-rose-400/30 bg-rose-500/10 p-3 text-xs text-rose-100">{{ copy.mainRequired }}</p><button class="mt-6 w-full rounded-full bg-amber-300 px-5 py-3 font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-60" :disabled="checkingOut || checkoutBlocked" @click="createOrder">{{ checkingOut ? copy.creating : copy.checkout }}</button><p class="mt-3 text-xs leading-5 text-slate-500">{{ copy.backendNotice }}</p></aside>
    </div>

    <section class="mt-10">
      <div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.25em] text-cyan-200">{{ copy.recovery }}</p><h2 class="mt-2 text-2xl font-black">{{ copy.pendingOrders }}</h2><p class="mt-2 text-sm text-slate-400">{{ copy.recoveryDescription }}</p></div><button class="rounded-full border border-white/20 px-4 py-2 text-sm font-semibold disabled:opacity-50" :disabled="ordersLoading" @click="loadPendingOrders">{{ ordersLoading ? copy.refreshing : copy.refresh }}</button></div>
      <div v-if="ordersLoading && !pendingOrders.length" class="glass-card mt-5 rounded-3xl p-6 text-slate-400">{{ copy.loadingPending }}</div>
      <p v-else-if="ordersError" role="alert" class="mt-5 text-red-200">{{ ordersError }}</p>
      <div v-else-if="!pendingOrders.length" class="mt-5 rounded-3xl border border-dashed border-white/15 p-6 text-sm text-slate-400">{{ copy.noPending }}</div>
      <div v-else class="mt-5 grid gap-5 lg:grid-cols-2">
        <article v-for="entry in pendingOrders" :key="entry.order.id" class="glass-card rounded-3xl p-5">
          <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs uppercase tracking-[.18em] text-slate-500">{{ entry.order.order_number }}</p><p class="mt-2 text-xl font-bold text-white">{{ usd(displayPendingTotal(entry)) }}</p><LocalCurrencyAmounts :amount="entry.order.total_amount" compact /></div><span class="rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-1 text-xs font-bold uppercase text-amber-100">{{ statusLabel(entry.order.status) }}</span></div>
          <ul class="mt-4 space-y-3 border-t border-white/10 pt-4"><li v-for="item in entry.items" :key="item.id" class="grid gap-2 text-sm sm:grid-cols-[1fr_auto]"><span class="min-w-0 break-words text-slate-300">{{ item.product_name }} × {{ item.quantity }}</span><div class="sm:text-right"><strong class="text-white">{{ usd(displayUnitPrice(item.product_id) * item.quantity) }}</strong><LocalCurrencyAmounts :amount="displayItemIdr(item.product_id, item.quantity, item.unit_price)" compact /></div></li></ul>
          <OrderPaymentProgress :order="entry.order" :attempts="entry.payment_attempts" @attempts-removed="ids => entry.payment_attempts = (entry.payment_attempts || []).filter(attempt => !ids.includes(attempt.id))" />
          <p v-if="entry.payment_attempts?.length" class="mt-4 text-xs text-slate-500">{{ copy.attempts.replace('{count}', String(entry.payment_attempts.length)) }}</p>
          <div class="mt-5 flex flex-col gap-2 sm:flex-row"><button v-if="entry.order.allowed_actions?.includes('continue_payment')" class="flex-1 rounded-full bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 disabled:opacity-50" :disabled="processingOrderId === entry.order.id" @click="continuePayment(entry)">{{ processingOrderId === entry.order.id ? copy.preparing : copy.continueWith.replace('{provider}', paymentProviderLabel) }}</button><button v-if="entry.order.allowed_actions?.includes('cancel')" class="rounded-full border border-red-300/30 px-5 py-3 text-sm font-bold text-red-200 disabled:opacity-50" :disabled="processingOrderId === entry.order.id" @click="cancelOrder(entry)">{{ copy.delete }}</button></div>
        </article>
      </div>
    </section>
  </section>
</template>
<script setup lang="ts">
import {useEvent} from '~/composables/useEvent';
import {hasMainPackageEntitlement,useStore,type StoreCart} from '~/composables/useStore';
import {usePayment,type PendingOrderRecord} from '~/composables/usePayment';
definePageMeta({middleware:'auth'});
const {locale}=useI18n();
const messages={
  en:{eyebrow:'Shopping cart',title:'Review your packages',description:'Package prices are shown in USD. The payment gateway will calculate the final payment amount.',addPackage:'Add another package',loading:'Loading your cart…',empty:'Your cart is empty',pendingSaved:'Your previously selected packages are saved in the pending orders below. Continue payment without selecting them again.',choosePackage:'Choose a delegate or exhibitor package to continue.',browse:'Browse packages',package:'Package',defaultPackage:'IWBIF Package',quantity:'Quantity',removing:'Removing…',remove:'Remove',summary:'Order summary',items:'Items',total:'Total',mainRequired:'Select one Main Delegate Package (A or B) before checkout.',creating:'Creating order…',checkout:'Proceed to checkout',backendNotice:'Package totals are displayed in USD; payment processing uses the backend payment configuration.',recovery:'Payment recovery',pendingOrders:'Pending Orders',recoveryDescription:'Continue an existing payment or remove an order you no longer wish to complete.',refreshing:'Refreshing…',refresh:'Refresh',loadingPending:'Loading pending orders…',noPending:'You have no pending orders.',attempts:'{count} payment attempt(s) recorded.',preparing:'Preparing payment…',continueWith:'Continue with {provider}',delete:'Delete',onlinePayment:'online payment',cartError:'Your cart could not be loaded.',noEvent:'No IWBIF event is currently published.',missingOrderId:'The backend did not return an order ID.',reasonPrompt:'Why do you want to remove order {order}?',defaultReason:'I no longer wish to continue this purchase.',confirmDelete:'Remove pending order {order}? This action cannot be undone from the cart.',seo:'Shopping Cart'},
  zh:{eyebrow:'购物车',title:'核对所选套餐',description:'套餐价格以美元显示。最终付款金额将由支付网关计算。',addPackage:'添加其他套餐',loading:'正在加载购物车…',empty:'您的购物车为空',pendingSaved:'您之前选择的套餐已保存在下方待处理订单中，无需重新选择即可继续付款。',choosePackage:'请选择代表或参展商套餐以继续。',browse:'浏览套餐',package:'套餐',defaultPackage:'IWBIF 套餐',quantity:'数量',removing:'正在移除…',remove:'移除',summary:'订单摘要',items:'项目数',total:'总计',mainRequired:'结账前请选择一个主要代表套餐（A 或 B）。',creating:'正在创建订单…',checkout:'前往结账',backendNotice:'套餐总额以美元显示；付款处理使用后端支付配置。',recovery:'恢复付款',pendingOrders:'待处理订单',recoveryDescription:'继续现有付款，或删除您不再希望完成的订单。',refreshing:'正在刷新…',refresh:'刷新',loadingPending:'正在加载待处理订单…',noPending:'您没有待处理订单。',attempts:'已记录 {count} 次付款尝试。',preparing:'正在准备付款…',continueWith:'使用 {provider} 继续付款',delete:'删除',onlinePayment:'在线付款',cartError:'无法加载您的购物车。',noEvent:'目前没有已发布的 IWBIF 活动。',missingOrderId:'后端未返回订单 ID。',reasonPrompt:'为什么要删除订单 {order}？',defaultReason:'我不再希望继续此次购买。',confirmDelete:'确定删除待处理订单 {order} 吗？此操作无法在购物车中撤销。',seo:'购物车'}
} as const;
const copy=computed(()=>String(locale.value) === 'zh-CN'?messages.zh:messages.en);
const statusLabel=(status:string)=>String(locale.value) === 'zh-CN'?({created:'已创建',pending:'待处理',failed:'失败',expired:'已过期',canceled:'已取消',cancelled:'已取消'}[status.toLowerCase()]||status):status;
useSeoMeta({title:()=>`${copy.value.seo} | IWBIF 2026`});
const {getEvents,getDelegatePackageCatalog}=useEvent();const storeApi=useStore();const paymentApi=usePayment();const eventId=ref('');const cart=ref<StoreCart|null>(null);const usdPricesByProductId=ref(new Map<string,number>());const idrPricesByProductId=ref(new Map<string,number>());const additionalOnlyEligible=ref(false);const loading=ref(true),checkingOut=ref(false),removingId=ref(''),errorMessage=ref('');
const pendingOrders=ref<PendingOrderRecord[]>([]),ordersLoading=ref(false),processingOrderId=ref(''),ordersError=ref('');const paymentProviderLabel=computed(()=>paymentApi.paymentProviderLabel||copy.value.onlinePayment);
const items=computed(()=>cart.value?.items||[]);const itemCount=computed(()=>items.value.reduce((total,item)=>total+item.quantity,0));const displayUnitPrice=(productId:string)=>usdPricesByProductId.value.get(productId)||0;const displayTotal=computed(()=>items.value.reduce((sum,item)=>sum+(displayUnitPrice(item.product_id)*item.quantity),0));
const displayItemIdr=(productId:string,quantity:number,fallback=0)=>(idrPricesByProductId.value.get(productId)||Number(fallback)||0)*quantity;const displayIdrTotal=computed(()=>items.value.reduce((sum,item)=>sum+displayItemIdr(item.product_id,item.quantity,item.unit_price),0));
const usd=(amount:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(amount||0);
const mainPackageRequired=computed(()=>items.value.some(item=>item.product?.product_type==='additional')&&!items.value.some(item=>item.product?.product_type==='delegate')&&!additionalOnlyEligible.value);
const checkoutBlocked=computed(()=>mainPackageRequired.value);
const apiError=(error:unknown)=>{const value=error as {data?:{message?:string;errors?:Array<{message:string}>}};return value.data?.errors?.[0]?.message||value.data?.message||(error instanceof Error?error.message:copy.value.cartError);};
const loadCart=async()=>{const events=await getEvents(1,1);const event=events.data[0];if(!event)throw new Error(copy.value.noEvent);eventId.value=event.id;const [cartResponse,additionalResponse,catalogResponse]=await Promise.all([storeApi.getCart(event.id),storeApi.getMyAdditionalProducts(event.id).catch(()=>null),getDelegatePackageCatalog(event.id)]);cart.value=cartResponse.data;const rates=[...catalogResponse.data.main_packages,...catalogResponse.data.additional_packages,...(catalogResponse.data.exhibitor_packages||[])].flatMap(pkg=>pkg.rates).filter(rate=>rate.is_active);usdPricesByProductId.value=new Map(rates.map(rate=>[rate.product_id,Number(rate.amount)]));idrPricesByProductId.value=new Map(rates.filter(rate=>rate.payment_amount_idr!=null).map(rate=>[rate.product_id,Number(rate.payment_amount_idr)]));additionalOnlyEligible.value=hasMainPackageEntitlement(additionalResponse?.data||[]);};
const loadPendingOrders=async()=>{ordersLoading.value=true;ordersError.value='';try{pendingOrders.value=await paymentApi.getOutstandingOrders();}catch(error){ordersError.value=apiError(error);}finally{ordersLoading.value=false;}};
const displayPendingTotal=(entry:PendingOrderRecord)=>entry.items.reduce((sum,item)=>sum+(displayUnitPrice(item.product_id)*item.quantity),0);
const remove=async(productId:string)=>{if(!eventId.value||removingId.value)return;removingId.value=productId;errorMessage.value='';try{cart.value=(await storeApi.removeCartItem(eventId.value,productId)).data;}catch(error){errorMessage.value=apiError(error);}finally{removingId.value='';}};
const createOrder=async()=>{if(!eventId.value||checkingOut.value||checkoutBlocked.value)return;checkingOut.value=true;errorMessage.value='';try{const order=(await storeApi.checkout(eventId.value)).data;const orderId=order.order_id||order.id;if(!orderId)throw new Error(copy.value.missingOrderId);sessionStorage.setItem('iwbif-store-order-id',orderId);sessionStorage.setItem('iwbif-store-order',JSON.stringify(order));await navigateTo(`/dashboard/payment?order_id=${encodeURIComponent(orderId)}`);}catch(error){errorMessage.value=apiError(error);}finally{checkingOut.value=false;}};
const continuePayment=async(entry:PendingOrderRecord)=>{await navigateTo(`/dashboard/payment?order_id=${encodeURIComponent(entry.order.id)}`);};
const cancelOrder=async(entry:PendingOrderRecord)=>{if(processingOrderId.value)return;const reason=window.prompt(copy.value.reasonPrompt.replace('{order}',entry.order.order_number),copy.value.defaultReason);if(reason===null||!reason.trim())return;if(!window.confirm(copy.value.confirmDelete.replace('{order}',entry.order.order_number)))return;processingOrderId.value=entry.order.id;errorMessage.value='';try{await paymentApi.cancelPendingOrder(entry.order.id,reason.trim());pendingOrders.value=pendingOrders.value.filter(item=>item.order.id!==entry.order.id);}catch(error){errorMessage.value=apiError(error);}finally{processingOrderId.value='';}};
onMounted(async()=>{try{await Promise.all([loadCart(),loadPendingOrders()]);}catch(error){errorMessage.value=apiError(error);}finally{loading.value=false;}});
</script>
