type LegalSection = { title: string; text: string };
type LegalDocument = { label: string; title: string; intro: string; sections: ReadonlyArray<LegalSection> };

const documents = {
  en: {
    privacy: { label:'Privacy Policy', title:'How we protect participant data at IWBIF.', intro:'We process participant information responsibly and only for legitimate event operations.', sections:[{title:'Data we collect',text:'Account details, professional profile data, event selections, tickets, payment records, and check-in activity needed to run IWBIF operations.'},{title:'How data is used',text:'Data supports registration, communication, ticket delivery, matching recommendations, networking, participant support, and event operations.'},{title:'Sharing and security',text:'Data is not sold. Access is limited to organizers and approved service providers; private contact data is never exposed without permission.'},{title:'Participant rights',text:'Participants can update profile details and privacy settings in the dashboard, including directory visibility.'}]},
    terms: { label:'Terms and Conditions', title:'Clear rules for a smooth registration and event journey.', intro:'These terms establish the responsibilities of participants and the organizer.', sections:[{title:'Registration and tickets',text:'Participants must provide accurate information. Tickets are personal and not transferable without approval.'},{title:'Payments',text:'Payment status follows confirmation from the configured payment provider and the organizer team process.'},{title:'Participant conduct',text:'Participants must respect others and maintain a harassment-free professional environment at all times.'},{title:'Program changes',text:'The organizer may adjust sessions, tracks, or venues as operationally needed and will communicate updates through official channels.'}]},
    conduct: { label:'Code of Conduct', title:'Create a respectful, safe, and professional business ecosystem.', intro:'Everyone participating in IWBIF is expected to uphold these standards.', sections:[{title:'Our commitment',text:'Every participant, speaker, partner, volunteer, and staff member deserves an inclusive and respectful forum experience.'},{title:'Expected behavior',text:'Communicate with professionalism, protect participant data, ask permission before recording, and follow all staff guidance and venue rules.'},{title:'Unacceptable behavior',text:'Harassment, intimidation, fraud, misuse of participant information, identity theft, and non-consensual sharing of codes or credentials are prohibited.'},{title:'Enforcement',text:'Violations may lead to a warning, removal from event activities, account suspension, registration cancellation, or referral to authorities.'}]},
    refund: { label:'Cancellation and Refund Policy', title:'Cancellation and Refund Policy', intro:'Ticket changes and refunds are handled fairly while protecting event commitments and payment costs.', sections:[{title:'Refund requests',text:'Refund eligibility follows the deadline and conditions communicated with the selected ticket. Administrative and payment processing fees may not be refundable.'},{title:'Ticket transfers',text:'Tickets cannot be transferred without organizer approval and all approved changes must be completed before the announced transfer deadline.'},{title:'Program changes',text:'Speaker, schedule, room, and track adjustments do not automatically qualify for a refund when the core forum continues as planned.'},{title:'Event cancellation',text:'If the organizer cancels the event, participants receive official instructions through the registered email about available remedies.'}]}
  },
  'zh-CN': {
    privacy: { label:'隐私政策', title:'IWBIF 如何保护参会者数据。', intro:'我们以负责任的方式处理参会者信息，且仅用于正当的活动运营。', sections:[{title:'我们收集的数据',text:'包括运营 IWBIF 所需的账户信息、职业资料、活动选择、门票、付款记录和签到活动。'},{title:'数据用途',text:'数据用于注册、通信、门票交付、配对建议、人脉交流、参会者支持和活动运营。'},{title:'共享与安全',text:'我们不会出售数据。访问权限仅限于主办方和经批准的服务提供商；未经许可绝不会公开私人联系数据。'},{title:'参会者权利',text:'参会者可在用户中心更新资料和隐私设置，包括名录可见性。'}]},
    terms: { label:'条款与条件', title:'为顺畅的注册与参会体验制定明确规则。', intro:'本条款明确参会者和主办方的责任。', sections:[{title:'注册与门票',text:'参会者必须提供准确信息。门票仅限本人使用，未经批准不得转让。'},{title:'付款',text:'付款状态以指定付款服务商的确认及主办团队的处理流程为准。'},{title:'参会者行为',text:'参会者必须尊重他人，并始终维护无骚扰的专业环境。'},{title:'议程变更',text:'主办方可根据运营需要调整专场、轨道或场地，并通过官方渠道通知更新。'}]},
    conduct: { label:'行为准则', title:'共建尊重、安全且专业的商业生态。', intro:'所有 IWBIF 参与者均应遵守以下标准。', sections:[{title:'我们的承诺',text:'每位参会者、演讲嘉宾、合作伙伴、志愿者和工作人员都应获得包容且受尊重的论坛体验。'},{title:'期望行为',text:'以专业方式沟通，保护参会者数据，录音录像前征得许可，并遵守工作人员指引和场地规则。'},{title:'不可接受的行为',text:'禁止骚扰、恐吓、欺诈、滥用参会者信息、身份盗用及未经同意共享代码或凭证。'},{title:'执行措施',text:'违规行为可能导致警告、移出活动、暂停账户、取消注册或移交相关机关。'}]},
    refund: { label:'取消与退款政策', title:'取消与退款政策', intro:'我们在保障活动承诺和付款成本的同时，公平处理门票变更与退款。', sections:[{title:'退款申请',text:'退款资格以所选门票公布的截止日期和条件为准。行政及付款处理费可能不予退还。'},{title:'门票转让',text:'未经主办方批准不得转让门票，所有获批变更必须在公布的转让截止日期前完成。'},{title:'议程变更',text:'若论坛主体按计划继续举行，演讲嘉宾、时间表、房间或轨道调整不会自动构成退款理由。'},{title:'活动取消',text:'如主办方取消活动，参会者将通过注册邮箱收到有关可用处理方案的官方说明。'}]}
  }
} as const;

export const useLegalContent = (key: 'privacy'|'terms'|'conduct'|'refund') => {
  const {locale}=useI18n();
  return computed<LegalDocument>(()=>documents[String(locale.value) === 'zh-CN'?'zh-CN':'en'][key]);
};
