type LegalSection = { title: string; text: string };
type LegalDocument = { label: string; title: string; intro: string; sections: ReadonlyArray<LegalSection> };

const documents = {
  en: {
    privacy: { label:'Privacy Policy', title:'How we protect participant data at Hari Santri 2026.', intro:'We process participant information responsibly and only for legitimate event operations.', sections:[{title:'Data we collect',text:'Account details, participant information, activity selections, tickets, payment records, and check-in activity needed to run the event.'},{title:'How data is used',text:'Data supports registration, event communication, ticket delivery, participant support, payment processing, and check-in.'},{title:'Sharing and security',text:'Data is not sold. Access is limited to organizers and approved service providers; private contact data is never exposed without permission.'},{title:'Participant rights',text:'Participants can update their profile details through the account dashboard and contact the organizer about privacy requests.'}]},
    terms: { label:'Terms and Conditions', title:'Clear rules for a smooth registration and event journey.', intro:'These terms establish the responsibilities of participants and the organizer.', sections:[{title:'Registration and tickets',text:'Participants must provide accurate information. Tickets are personal and not transferable without approval.'},{title:'Payments',text:'Payment status follows confirmation from the configured payment provider and the organizer team process.'},{title:'Participant conduct',text:'Participants must respect others and maintain a harassment-free professional environment at all times.'},{title:'Program changes',text:'The organizer may adjust sessions, tracks, or venues as operationally needed and will communicate updates through official channels.'}]},
    conduct: { label:'Code of Conduct', title:'Create a respectful and safe event experience.', intro:'Everyone participating in Hari Santri 2026 is expected to uphold these standards.', sections:[{title:'Our commitment',text:'Every participant, organizer, volunteer, and staff member deserves an inclusive and respectful event experience.'},{title:'Expected behavior',text:'Communicate respectfully, protect participant data, ask permission before recording, and follow staff guidance and venue rules.'},{title:'Unacceptable behavior',text:'Harassment, intimidation, fraud, misuse of participant information, identity theft, and non-consensual sharing of codes or credentials are prohibited.'},{title:'Enforcement',text:'Violations may lead to a warning, removal from event activities, account suspension, registration cancellation, or referral to authorities.'}]},
    refund: { label:'Cancellation and Refund Policy', title:'Cancellation and Refund Policy', intro:'Registration changes and refunds are handled fairly while protecting event commitments and payment costs.', sections:[{title:'Refund requests',text:'Refund eligibility follows the deadline and conditions communicated during registration. Administrative and payment processing fees may not be refundable.'},{title:'Ticket transfers',text:'Tickets cannot be transferred without organizer approval and all approved changes must be completed before the announced transfer deadline.'},{title:'Program changes',text:'Schedule, activity, or venue adjustments do not automatically qualify for a refund when the event continues as planned.'},{title:'Event cancellation',text:'If the organizer cancels the event, participants receive official instructions through the registered email about available remedies.'}]}
  },
  id: {
    privacy: { label:'Kebijakan Privasi', title:'Cara kami menjaga data peserta Hari Santri 2026.', intro:'Kami mengelola informasi peserta secara bertanggung jawab dan hanya untuk kebutuhan penyelenggaraan acara.', sections:[{title:'Data yang dikumpulkan',text:'Data akun, informasi peserta, pilihan kegiatan, tiket, catatan pembayaran, dan kehadiran yang diperlukan untuk menjalankan acara.'},{title:'Penggunaan data',text:'Data digunakan untuk pendaftaran, komunikasi acara, penerbitan tiket, dukungan peserta, pemrosesan pembayaran, dan check-in.'},{title:'Keamanan dan pembagian data',text:'Data tidak diperjualbelikan. Akses dibatasi untuk panitia dan penyedia layanan yang disetujui; informasi kontak pribadi tidak dibagikan tanpa izin.'},{title:'Hak peserta',text:'Peserta dapat memperbarui profil melalui dashboard akun dan menghubungi panitia untuk permintaan terkait privasi.'}]},
    terms: { label:'Syarat dan Ketentuan', title:'Ketentuan pendaftaran dan keikutsertaan acara.', intro:'Ketentuan ini menjelaskan tanggung jawab peserta dan penyelenggara.', sections:[{title:'Pendaftaran dan tiket',text:'Peserta wajib memberikan informasi yang akurat. Tiket berlaku untuk pemiliknya dan tidak dapat dialihkan tanpa persetujuan panitia.'},{title:'Pembayaran',text:'Status pembayaran mengikuti konfirmasi penyedia pembayaran dan proses verifikasi panitia.'},{title:'Perilaku peserta',text:'Peserta wajib menghormati orang lain dan menjaga lingkungan acara yang aman serta bebas dari pelecehan.'},{title:'Perubahan acara',text:'Panitia dapat menyesuaikan jadwal, kegiatan, atau lokasi bila diperlukan dan akan menyampaikan perubahan melalui kanal resmi.'}]},
    conduct: { label:'Tata Tertib', title:'Wujudkan pengalaman acara yang aman dan saling menghormati.', intro:'Seluruh peserta Hari Santri 2026 diharapkan mematuhi tata tertib berikut.', sections:[{title:'Komitmen kami',text:'Setiap peserta, panitia, relawan, dan petugas berhak mendapatkan pengalaman acara yang inklusif dan saling menghormati.'},{title:'Perilaku yang diharapkan',text:'Berkomunikasilah dengan santun, jaga data peserta, minta izin sebelum merekam, dan ikuti arahan petugas serta aturan lokasi.'},{title:'Perilaku yang dilarang',text:'Pelecehan, intimidasi, penipuan, penyalahgunaan informasi peserta, pencurian identitas, serta penyebaran kode atau kredensial tanpa izin dilarang.'},{title:'Penegakan aturan',text:'Pelanggaran dapat berakibat teguran, dikeluarkan dari kegiatan, penangguhan akun, pembatalan pendaftaran, atau pelaporan kepada pihak berwenang.'}]},
    refund: { label:'Kebijakan Pembatalan dan Pengembalian Dana', title:'Kebijakan Pembatalan dan Pengembalian Dana', intro:'Perubahan pendaftaran dan pengembalian dana ditangani secara adil dengan mempertimbangkan komitmen acara dan biaya pembayaran.', sections:[{title:'Permintaan pengembalian dana',text:'Pengembalian dana mengikuti batas waktu dan ketentuan yang disampaikan saat pendaftaran. Biaya administrasi dan pemrosesan pembayaran mungkin tidak dapat dikembalikan.'},{title:'Pengalihan tiket',text:'Tiket tidak dapat dialihkan tanpa persetujuan panitia. Perubahan yang disetujui harus diselesaikan sebelum batas waktu yang diumumkan.'},{title:'Perubahan acara',text:'Perubahan jadwal, kegiatan, atau lokasi tidak otomatis menjadi alasan pengembalian dana selama acara tetap berlangsung.'},{title:'Pembatalan acara',text:'Jika acara dibatalkan oleh panitia, peserta akan menerima petunjuk resmi melalui email yang digunakan saat pendaftaran.'}]}
  }
} as const;

export const useLegalContent = (key: 'privacy'|'terms'|'conduct'|'refund') => {
  const {locale}=useI18n();
  return computed<LegalDocument>(()=>documents[String(locale.value) === 'id'?'id':'en'][key]);
};
