<template>
  <section class="mx-auto max-w-7xl px-3 py-10 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-end justify-between gap-5">
      <div><p class="text-sm uppercase tracking-[.3em] text-cyan-200">Event operations</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Speakers</h1><p class="mt-3 text-sm leading-7 text-slate-300">Manage speaker profiles, publication, event placement, and photos.</p></div>
      <div class="flex flex-wrap gap-3"><NuxtLink to="/#pengisi-acara" class="action-secondary">View event performers</NuxtLink><button class="action-primary" :disabled="!selectedEventId" :title="selectedEventId ? 'Add speaker' : 'Select event first'" @click="openCreate">+ New speaker</button></div>
    </div>
    <p v-if="feedback" class="mt-5 rounded-2xl border p-4 text-sm" :class="feedbackTone === 'error' ? 'border-red-300/30 bg-red-950/30 text-red-100' : 'border-emerald-300/30 bg-emerald-950/30 text-emerald-100'">{{ feedback }}</p>

    <div class="mt-8 flex flex-col gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-4 sm:flex-row sm:items-end">
      <label class="relative block w-full sm:max-w-sm"><span class="sr-only">Search speakers</span><input v-model.trim="search" class="w-full rounded-full border border-white/10 bg-slate-950/70 px-5 py-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-cyan-300/50" placeholder="Search name or organization..." /></label>
      <label class="field sm:w-32"><span>Per page</span><select v-model.number="pageSize"><option :value="10">10</option><option :value="20">20</option><option :value="50">50</option></select></label>
      <p class="pb-3 text-sm text-slate-400">{{ tableMeta.total }} speakers</p>
    </div>

    <div class="mt-6 overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/45 shadow-2xl shadow-slate-950/30"><div class="data-table-shell overflow-x-auto">
      <table class="w-full min-w-full text-left md:min-w-[900px]"><thead class="border-b border-white/10 bg-white/[.045] text-[11px] uppercase tracking-[.18em] text-slate-400"><tr><th class="px-5 py-4">Speaker</th><th class="px-5 py-4">Organization</th><th class="px-5 py-4">Country</th><th class="px-5 py-4">Expertise</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Actions</th></tr></thead>
        <tbody class="divide-y divide-white/[.07]">
          <tr v-if="pending"><td colspan="6" class="px-5 py-12 text-center text-slate-400">Loading speakers...</td></tr><tr v-else-if="!filteredSpeakers.length"><td colspan="6" class="px-5 py-12 text-center text-slate-400">No speakers found.</td></tr>
          <tr v-for="speaker in paginatedSpeakers" v-else :key="speaker.id" class="transition hover:bg-cyan-300/[.035]">
            <td class="px-5 py-4" data-label="Speaker"><div class="flex items-center gap-3"><img v-if="speaker.profile_photo_url" :src="mediaUrl(speaker.profile_photo_url)" :alt="speaker.full_name" class="h-12 w-12 rounded-xl object-cover ring-1 ring-white/10" /><div v-else class="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-300/10 font-bold text-cyan-200">{{ initials(speaker.full_name) }}</div><div class="min-w-0"><p class="break-words font-bold text-white">{{ speaker.full_name }}</p><p class="mt-1 break-words text-xs text-slate-400">{{ speaker.professional_title || 'Speaker' }}</p></div></div></td>
            <td class="px-5 py-4 text-sm text-slate-300 break-words" data-label="Organization">{{ speaker.organization_name || '—' }}</td><td class="px-5 py-4 text-sm uppercase text-slate-300" data-label="Country">{{ speaker.country_code || '—' }}</td><td class="px-5 py-4" data-label="Expertise"><div class="flex max-w-xs flex-wrap gap-1"><span v-for="tag in (speaker.expertise_tags || []).slice(0,2)" :key="tag" class="rounded-full bg-white/[.07] px-2 py-1 text-[10px] text-slate-300">{{ tag }}</span><span v-if="(speaker.expertise_tags || []).length > 2" class="text-xs text-slate-500">+{{ speaker.expertise_tags!.length - 2 }}</span></div></td>
            <td class="px-5 py-4" data-label="Status"><span class="status-pill" :class="speaker.status === 'published' ? 'status-live' : 'status-draft'">{{ speaker.status || 'published' }}</span><span class="status-pill ml-2" :class="translationStatuses[speaker.id] === 'complete' ? 'translation-complete' : translationStatuses[speaker.id] === 'error' ? 'translation-error' : 'translation-missing'">ZH {{ translationStatuses[speaker.id] === 'complete' ? 'complete' : translationStatuses[speaker.id] === 'error' ? 'unknown' : translationStatuses[speaker.id] === 'loading' ? 'checking' : 'missing' }}</span><span v-if="speaker.is_featured" class="ml-2 text-amber-200" title="Featured">★</span></td>
            <td class="px-5 py-4 cell-actions" data-label="Actions"><div class="flex flex-wrap justify-end gap-2"><button class="table-button" @click="openEdit(speaker)">Edit</button><button class="table-button border-red-300/20 text-red-200 hover:border-red-300/50" @click="removeSpeaker(speaker)">Delete</button></div></td>
          </tr>
        </tbody>
      </table>
    </div></div>
    <div class="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-400"><span>Showing {{ pageStart }}–{{ pageEnd }} of {{ tableMeta.total }}</span><div class="flex items-center gap-3"><button class="table-button" :disabled="currentPage <= 1" @click="currentPage--">Previous</button><span>Page {{ currentPage }} of {{ totalPages }}</span><button class="table-button" :disabled="currentPage >= totalPages" @click="currentPage++">Next</button></div></div>

    <Teleport to="body"><div v-if="modalOpen" class="modal-backdrop"><form class="modal-card" @submit.prevent="saveSpeaker">
      <div class="flex items-start justify-between gap-4 border-b border-white/10 px-5 py-5 sm:px-7"><div><p class="text-xs uppercase tracking-[.24em] text-cyan-200">Speaker editor</p><h2 class="mt-2 text-2xl font-black">{{ editingId ? 'Update speaker' : 'Create speaker' }}</h2><p class="mt-2 text-xs text-slate-400">Admin controls remain in English. Content can be maintained in English and Simplified Chinese.</p></div><button type="button" class="modal-close" aria-label="Close" @click="closeModal">×</button></div>
      <div class="max-h-[70vh] space-y-5 overflow-y-auto px-5 py-6 sm:px-7">
        <div class="flex flex-wrap gap-2 rounded-full border border-white/10 bg-slate-950/60 p-1.5">
          <button type="button" class="language-tab" :class="activeTab === 'en' && 'language-tab-active'" @click="activeTab = 'en'">English — Source</button>
          <button type="button" class="language-tab" :class="activeTab === 'zh-CN' && 'language-tab-active'" @click="activeTab = 'zh-CN'">简体中文 <span class="ml-1 rounded-full px-2 py-0.5 text-[10px]" :class="translationExists ? 'bg-emerald-300/15 text-emerald-200' : 'bg-amber-300/15 text-amber-200'">{{ translationLoading ? 'Loading' : translationExists ? 'Complete' : 'Missing' }}</span></button>
        </div>
        <div v-if="activeTab === 'en'" class="space-y-5">
        <div class="flex flex-col gap-4 rounded-2xl border bg-white/[.035] p-4 sm:flex-row sm:items-center" :class="photoError ? 'border-red-300/40 bg-red-950/20' : 'border-white/10'">
          <img v-if="photoPreview" :src="photoPreview" alt="Speaker photo preview" class="h-24 w-24 rounded-2xl object-cover" /><div v-else class="flex h-24 w-24 shrink-0 items-center justify-center rounded-2xl bg-cyan-300/10 text-2xl font-bold text-cyan-200">{{ initials(form.full_name || 'Speaker') }}</div>
          <div><p class="font-semibold">Profile photo</p><p class="mt-1 text-xs leading-5 text-slate-400">JPG, PNG, or WebP; maximum 5 MB.</p><p v-if="photoError" role="alert" class="mt-2 text-sm font-semibold text-red-200">{{ photoError }}</p><label class="mt-3 inline-flex cursor-pointer rounded-full bg-white/10 px-4 py-2 text-xs font-bold text-cyan-100 hover:bg-white/15"><span>{{ selectedPhoto ? 'Change selected photo' : editingId ? 'Replace photo' : 'Choose photo' }}</span><input class="sr-only" type="file" accept="image/jpeg,image/png,image/webp" @change="selectPhoto" /></label></div>
        </div>
        <label v-if="!editingId" class="field"><span>Event</span><select v-model="selectedEventId"><option value="" disabled>Select event</option><option v-for="event in events" :key="event.id" :value="event.id">{{ event.name }}</option></select><small v-if="!selectedEventId" class="mt-2 block text-xs text-amber-200">Select an event before creating a speaker.</small></label>
        <div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Full name</span><input v-model.trim="form.full_name" required /></label><label class="field"><span>Professional title</span><input v-model.trim="form.professional_title" /></label></div>
        <div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Organization</span><input v-model.trim="form.organization_name" /></label><label class="field"><span>Country code</span><input v-model.trim="form.country_code" maxlength="3" placeholder="IDN" /></label></div>
        <label class="field"><span>Biography</span><textarea v-model.trim="form.biography" rows="4" /></label><label class="field"><span>Expertise (comma separated)</span><input v-model.trim="expertiseText" placeholder="Investment, Global Trade" /></label><label class="field"><span>Session title</span><input v-model.trim="form.session_title" /></label>
        <div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>LinkedIn URL</span><input v-model.trim="form.linkedin_url" type="url" /></label><label class="field"><span>Website URL</span><input v-model.trim="form.website_url" type="url" /></label></div>
        <div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Status</span><select v-model="form.status"><option value="draft">Draft</option><option value="published">Published</option></select></label><label class="flex items-center gap-3 pt-7 text-sm text-slate-300"><input v-model="form.is_featured" type="checkbox" /> Featured speaker</label></div>
        </div>
        <div v-else class="space-y-5">
          <div class="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] p-4 text-sm leading-6 text-slate-300"><strong class="text-cyan-100">Source reference:</strong> {{ form.full_name || 'Save the English source first.' }}<br />Full name, country, URLs, status, featured state, and photo remain canonical and are not translated.</div>
          <p v-if="translationLoading" class="rounded-2xl border border-white/10 p-4 text-sm text-slate-400">Loading Simplified Chinese translation...</p>
          <template v-else>
            <div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Professional title (简体中文)</span><input v-model.trim="zhForm.professional_title" :placeholder="form.professional_title || '首席执行官'" /></label><label class="field"><span>Organization (简体中文)</span><input v-model.trim="zhForm.organization_name" :placeholder="form.organization_name || '机构名称'" /></label></div>
            <label class="field"><span>Biography (简体中文)</span><textarea v-model.trim="zhForm.biography" rows="4" :placeholder="form.biography || '请输入中文简介'" /></label>
            <label class="field"><span>Expertise (简体中文, comma separated)</span><input v-model.trim="zhExpertiseText" :placeholder="expertiseText || '投资, 国际贸易'" /></label>
            <label class="field"><span>Session title (简体中文)</span><input v-model.trim="zhForm.session_title" :placeholder="form.session_title || '请输入中文专场标题'" /></label>
            <div v-if="translationExists" class="flex justify-end"><button type="button" class="rounded-full border border-red-300/25 px-4 py-2 text-xs font-bold text-red-200 hover:border-red-300/60" :disabled="saving" @click="removeChineseTranslation">Delete Chinese translation</button></div>
          </template>
        </div>
      </div>
      <div class="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-5 py-5 sm:px-7"><p class="text-xs text-slate-400">English is saved first; Chinese is saved independently when filled.</p><div class="flex gap-3"><button type="button" class="action-secondary" @click="closeModal">Cancel</button><button class="action-primary" :disabled="saving || translationLoading">{{ saving ? 'Saving...' : 'Save content' }}</button></div></div>
    </form></div></Teleport>
  </section>
</template>

<script setup lang="ts">
import { useTableReload } from '~/composables/useTableReload';
import { useSpeaker } from '~/composables/useSpeaker'; import { useAdminContent, type SpeakerMutationPayload } from '~/composables/useAdminContent'; import { useEvent, type EventItem, type SpeakerItem } from '~/composables/useEvent';
definePageMeta({ middleware: ['auth','admin'] }); useSeoMeta({ title:'Manage Speakers | Hari Santri 2026' });
const {getSpeakers,uploadSpeakerPhoto}=useSpeaker(); const adminApi=useAdminContent(); const {getEvents}=useEvent(); const {mediaUrl}=useMediaUrl();
const pending=ref(false); const speakers=ref<SpeakerItem[]>([]); const {data:eventResponse}=useAsyncData('admin-speaker-events',()=>getEvents(1,100)); const events=computed<EventItem[]>(()=>eventResponse.value?.data||[]); const selectedEventId=ref('');
const search=ref(''); const filteredSpeakers=computed(()=>speakers.value);
const currentPage=ref(1),pageSize=ref(20);const tableMeta=reactive({total:0,pages:0});const totalPages=computed(()=>Math.max(1,tableMeta.pages));const paginatedSpeakers=computed(()=>speakers.value);const pageStart=computed(()=>speakers.value.length?(currentPage.value-1)*pageSize.value+1:0);const pageEnd=computed(()=>Math.min((currentPage.value-1)*pageSize.value+speakers.value.length,tableMeta.total));
const modalOpen=ref(false),editingId=ref(''),saving=ref(false),feedback=ref(''); const feedbackTone=ref<'success'|'error'>('success'),expertiseText=ref(''); const selectedPhoto=ref<File|null>(null),photoPreview=ref(''),photoError=ref('');
type SpeakerTranslationFields=Record<string,unknown>&{professional_title?:string;organization_name?:string;biography?:string;expertise_tags?:string[];session_title?:string};
const activeTab=ref<'en'|'zh-CN'>('en'),translationLoading=ref(false),translationExists=ref(false),zhExpertiseText=ref('');
const translationStatuses=ref<Record<string,'loading'|'complete'|'missing'|'error'>>({});
const emptyZhForm=()=>({professional_title:'',organization_name:'',biography:'',session_title:''}); const zhForm=reactive(emptyZhForm());
const emptyForm=():SpeakerMutationPayload=>({full_name:'',professional_title:'',organization_name:'',country_code:'',biography:'',linkedin_url:'',website_url:'',session_title:'',is_featured:false,status:'published'}); const form=reactive<SpeakerMutationPayload>(emptyForm());
const initials=(name:string)=>name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase(); const apiError=(error:unknown)=>{const value=error as {data?:{message?:string;request_id?:string;errors?:Array<{code?:string;message:string}>}};const detail=value.data?.errors?.[0];const messages:Record<string,string>={INVALID_IMAGE_TYPE:'Format foto tidak didukung. Gunakan JPG, PNG, atau WebP.',EMPTY_IMAGE:'File foto kosong. Pilih file gambar lain.',IMAGE_TOO_LARGE:'Ukuran foto melebihi batas maksimum 5 MB.',SPEAKER_NOT_FOUND:'Data speaker tidak ditemukan.',UPLOAD_STORAGE_ERROR:'Foto tidak dapat disimpan karena penyimpanan server tidak tersedia atau tidak memiliki izin tulis. Hubungi administrator dan sertakan Request ID.'};const message=(detail?.code&&messages[detail.code])||detail?.message||value.data?.message||(error instanceof Error?error.message:'Speaker could not be saved.');return value.data?.request_id?`${message} (Request ID: ${value.data.request_id})`:message;};
const clearPreview=()=>{if(photoPreview.value.startsWith('blob:'))URL.revokeObjectURL(photoPreview.value);photoPreview.value='';selectedPhoto.value=null;photoError.value='';}; const resetForm=()=>{editingId.value='';expertiseText.value='';zhExpertiseText.value='';translationExists.value=false;translationLoading.value=false;activeTab.value='en';clearPreview();Object.assign(form,emptyForm());Object.assign(zhForm,emptyZhForm());};
const loadChineseTranslation=async(speakerId:string)=>{translationLoading.value=true;try{const translations=(await adminApi.getContentTranslations<SpeakerTranslationFields>('speaker',speakerId)).data||[];const translation=translations.find(item=>item.locale==='zh-CN');translationExists.value=Boolean(translation);const fields=translation?.fields||{};Object.assign(zhForm,{professional_title:String(fields.professional_title||''),organization_name:String(fields.organization_name||''),biography:String(fields.biography||''),session_title:String(fields.session_title||'')});zhExpertiseText.value=Array.isArray(fields.expertise_tags)?fields.expertise_tags.map(String).join(', '):'';}catch(error){feedbackTone.value='error';feedback.value=`Chinese translation could not be loaded. ${apiError(error)}`;}finally{translationLoading.value=false;}};
const openCreate=()=>{if(!selectedEventId.value){feedbackTone.value='error';feedback.value='Select an event before creating a speaker.';return;}resetForm();modalOpen.value=true;}; const openEdit=async(speaker:SpeakerItem)=>{resetForm();editingId.value=speaker.id;expertiseText.value=(speaker.expertise_tags||[]).join(', ');photoPreview.value=speaker.profile_photo_url?mediaUrl(speaker.profile_photo_url):'';Object.assign(form,{full_name:speaker.full_name,professional_title:speaker.professional_title||'',organization_name:speaker.organization_name||'',country_code:speaker.country_code||'',biography:speaker.biography||'',linkedin_url:speaker.linkedin_url||'',website_url:speaker.website_url||'',session_title:speaker.session_title||'',is_featured:speaker.is_featured||false,status:speaker.status||'published'});modalOpen.value=true;await loadChineseTranslation(speaker.id);}; const closeModal=()=>{modalOpen.value=false;resetForm();};
const loadTranslationStatuses=async()=>{translationStatuses.value=Object.fromEntries(speakers.value.map(item=>[item.id,'loading'])) as Record<string,'loading'|'complete'|'missing'|'error'>;await Promise.all(speakers.value.map(async item=>{try{const rows=(await adminApi.getContentTranslations('speaker',item.id)).data||[];translationStatuses.value[item.id]=rows.some(row=>row.locale==='zh-CN')?'complete':'missing';}catch{translationStatuses.value[item.id]='error';}}));};
const selectPhoto=(event:Event)=>{const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;const allowedTypes=new Set(['image/jpeg','image/png','image/webp']);photoError.value='';if(file.size>5*1024*1024){photoError.value=`Ukuran foto ${Math.ceil(file.size/1024/1024*10)/10} MB melebihi batas maksimum 5 MB.`;input.value='';return;}if(file.size===0){photoError.value='File foto kosong. Pilih file gambar lain.';input.value='';return;}if(!allowedTypes.has(file.type)){photoError.value='Format foto tidak didukung. Gunakan JPG, PNG, atau WebP.';input.value='';return;}clearPreview();feedback.value='';selectedPhoto.value=file;photoPreview.value=URL.createObjectURL(file);}; let tableRequestId=0;const reload=async()=>{const requestId=++tableRequestId;pending.value=true;try{const result=await getSpeakers(currentPage.value,pageSize.value,'en',search.value);if(requestId!==tableRequestId)return;speakers.value=result.data||[];Object.assign(tableMeta,{total:result.meta?.total??0,pages:result.meta?.pages??0});await loadTranslationStatuses();}catch(error){if(requestId===tableRequestId){feedbackTone.value='error';feedback.value=apiError(error);}}finally{if(requestId===tableRequestId)pending.value=false;}};
const hasChineseContent=()=>Object.values(zhForm).some(value=>value.trim())||Boolean(zhExpertiseText.value.trim());
const chinesePayload=():SpeakerTranslationFields=>{
  const fields:SpeakerTranslationFields={};
  const professionalTitle=zhForm.professional_title.trim();
  const organizationName=zhForm.organization_name.trim();
  const biography=zhForm.biography.trim();
  const expertiseTags=zhExpertiseText.value.split(',').map(item=>item.trim()).filter(Boolean);
  const sessionTitle=zhForm.session_title.trim();
  if(professionalTitle)fields.professional_title=professionalTitle;
  if(organizationName)fields.organization_name=organizationName;
  if(biography)fields.biography=biography;
  if(expertiseTags.length)fields.expertise_tags=expertiseTags;
  if(sessionTitle)fields.session_title=sessionTitle;
  return fields;
};
const saveSpeaker=async()=>{if(saving.value)return;saving.value=true;let sourceSaved=false;let photoSaved=!selectedPhoto.value;const payload:SpeakerMutationPayload={...form,professional_title:form.professional_title||null,organization_name:form.organization_name||null,country_code:form.country_code?.toUpperCase()||null,biography:form.biography||null,linkedin_url:form.linkedin_url||null,website_url:form.website_url||null,session_title:form.session_title||null,expertise_tags:expertiseText.value.split(',').map(item=>item.trim()).filter(Boolean)};try{let speakerId=editingId.value;if(speakerId){const updated=await adminApi.updateSpeaker(speakerId,payload);speakerId=updated.data.id;}else{if(!selectedEventId.value)throw new Error('Select a valid event before saving.');const created=await adminApi.createSpeaker(payload);speakerId=created.data.id;await adminApi.attachSpeakerToEvent(speakerId,selectedEventId.value);editingId.value=speakerId;}sourceSaved=true;if(selectedPhoto.value){await uploadSpeakerPhoto(speakerId,selectedPhoto.value);selectedPhoto.value=null;photoSaved=true;}if(hasChineseContent()){try{await adminApi.saveContentTranslation('speaker',speakerId,chinesePayload());translationExists.value=true;}catch(error){feedbackTone.value='error';feedback.value=`English source${photoSaved?' and photo':''} saved, but the Chinese translation failed. ${apiError(error)}`;activeTab.value='zh-CN';await reload();return;}}feedbackTone.value='success';feedback.value=hasChineseContent()?'English source and Chinese translation saved.':'English source saved. Chinese translation remains missing.';closeModal();await reload();}catch(error){feedbackTone.value='error';feedback.value=sourceSaved&&!photoSaved?`Speaker data was saved, but the photo upload failed. ${apiError(error)}`:apiError(error);if(sourceSaved)await reload();}finally{saving.value=false;}};
const removeChineseTranslation=async()=>{if(!editingId.value||saving.value)return;if(!window.confirm('Delete the Simplified Chinese translation? The English source will remain unchanged.'))return;if(!window.confirm('Confirm again: remove this Chinese translation and use English fallback on public pages?'))return;saving.value=true;try{await adminApi.deleteContentTranslation('speaker',editingId.value);Object.assign(zhForm,emptyZhForm());zhExpertiseText.value='';translationExists.value=false;feedbackTone.value='success';feedback.value='Chinese translation deleted. Public Chinese pages will use the English fallback.';}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}finally{saving.value=false;}};
const removeSpeaker=async(speaker:SpeakerItem)=>{if(!window.confirm(`Delete speaker "${speaker.full_name}"?`))return;try{await adminApi.deleteSpeaker(speaker.id);feedbackTone.value='success';feedback.value='Speaker deleted.';await reload();}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}};watch(events,(value)=>{if(!selectedEventId.value)selectedEventId.value=value[0]?.id||'';},{immediate:true});useTableReload(search,currentPage,pageSize,reload);watch(totalPages,value=>{if(currentPage.value>value)currentPage.value=value;});onBeforeUnmount(clearPreview);
await reload();
</script>

<style scoped>
section { font-family: 'Plus Jakarta Sans', 'Segoe UI', sans-serif; }
.field{display:block;font-size:.875rem;color:#cbd5e1}.field span{display:block;margin-bottom:.5rem}.field input,.field select,.field textarea{width:100%;border:1px solid rgba(255,255,255,.1);border-radius:1rem;background:rgba(2,6,23,.82);padding:.75rem 1rem;color:white;outline:none}.field input:focus,.field select:focus,.field textarea:focus{border-color:rgba(103,232,249,.55);box-shadow:0 0 0 3px rgba(103,232,249,.08)}
.action-primary,.action-secondary,.table-button{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:.7rem 1.15rem;font-size:.875rem;font-weight:700;transition:.18s}.action-primary{background:#67e8f9;color:#082f49}.action-primary:hover{filter:brightness(1.08)}.action-primary:disabled{opacity:.5}.action-secondary,.table-button{border:1px solid rgba(255,255,255,.15);color:#e2e8f0}.action-secondary:hover,.table-button:hover{border-color:rgba(103,232,249,.45);color:white}.table-button{padding:.45rem .85rem;font-size:.75rem}.status-pill{display:inline-flex;border-radius:999px;padding:.35rem .7rem;font-size:.65rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.status-live{background:rgba(52,211,153,.12);color:#a7f3d0}.status-draft{background:rgba(251,191,36,.12);color:#fde68a}
.language-tab{flex:1;border-radius:999px;padding:.65rem 1rem;font-size:.78rem;font-weight:700;color:#94a3b8;transition:.18s}.language-tab:hover{color:#e2e8f0}.language-tab-active{background:rgba(103,232,249,.13);color:#cffafe;box-shadow:inset 0 0 0 1px rgba(103,232,249,.28)}
.translation-complete{background:rgba(52,211,153,.12);color:#a7f3d0}.translation-missing{background:rgba(251,191,36,.12);color:#fde68a}.translation-error{background:rgba(248,113,113,.12);color:#fecaca}
.modal-backdrop{position:fixed;inset:0;z-index:100;display:flex;align-items:center;justify-content:center;background:rgba(2,6,23,.78);padding:1rem;backdrop-filter:blur(12px)}.modal-card{width:min(100%,52rem);overflow:hidden;border:1px solid rgba(255,255,255,.13);border-radius:2rem;background:linear-gradient(145deg,#071a36,#020d20);color:white;box-shadow:0 35px 100px rgba(0,0,0,.55)}.modal-close{display:flex;height:2.5rem;width:2.5rem;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.12);border-radius:999px;font-size:1.5rem;color:#cbd5e1}
@media (max-width: 767px) {
  .data-table-shell { overflow: visible; }
  .data-table-shell table, .data-table-shell thead, .data-table-shell tbody, .data-table-shell tr, .data-table-shell th, .data-table-shell td { display: block; width: 100%; box-sizing: border-box; }
  .data-table-shell thead { display: none; }
  .data-table-shell tbody { display: grid; gap: 0.75rem; padding: 0.75rem; }
  .data-table-shell tr { border: 1px solid rgba(255,255,255,.08); border-radius: 1.1rem; background: rgba(15,23,42,.72); padding: 0.8rem; }
  .data-table-shell td { border: 0; padding: 0.35rem 0; display: flex; justify-content: space-between; gap: 0.75rem; font-size: .8rem; }
  .data-table-shell td::before { content: attr(data-label); color: #94a3b8; font-size: .64rem; letter-spacing: .14em; text-transform: uppercase; width: 36%; flex-shrink: 0; }
  .data-table-shell td > * { flex: 1; min-width: 0; }
  .data-table-shell td.cell-actions { flex-direction: column; align-items: stretch; }
  .data-table-shell td.cell-actions::before { width: 100%; margin-bottom: 0.25rem; }
  .data-table-shell td.cell-actions > div { justify-content: stretch; }
  .data-table-shell td.cell-actions .table-button { width: 100%; }
}
</style>
